<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_customerNameSFa6K</name>
   <tag></tag>
   <elementGuidId>5df0d168-e40d-491f-b5f3-3138d8671dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.mat-cell.cdk-cell.cdk-column-name.mat-column-name.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-customelist-customermanagement']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0704bcfe-e850-4e83-a467-8a8edfbe17c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>59e0ab81-63f7-463b-a9d9-ed10c9fd39a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell cdk-column-name mat-column-name ng-star-inserted</value>
      <webElementGuid>a665bc6d-dd60-4c2c-8663-ee81ca8ac8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> customerNameSFa6K </value>
      <webElementGuid>7e43c483-170e-4d5d-b1bb-982dea5ef930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-customelist-customermanagement&quot;)/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-name mat-column-name ng-star-inserted&quot;]</value>
      <webElementGuid>05b039ff-03cc-4310-ab48-e63921590043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-customelist-customermanagement']/tbody/tr/td[2]</value>
      <webElementGuid>468d2739-0330-4d04-ab4c-8bf0615763a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customeridSFa6K'])[1]/following::td[1]</value>
      <webElementGuid>967346bf-8fa4-49e5-b31c-8afafb7bebb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::td[2]</value>
      <webElementGuid>8bbabefe-e18a-4e23-ae9c-f2a6f8e5ccae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PICSFa6K'])[1]/preceding::td[1]</value>
      <webElementGuid>724d195d-faff-4f38-86ee-d3c2e08f41ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emailSFa6K@mailinator.com'])[1]/preceding::td[2]</value>
      <webElementGuid>321d113c-9f17-4230-9127-bb98a5ba73cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='customerNameSFa6K']/parent::*</value>
      <webElementGuid>8f17a9b7-aab0-4772-9899-454a0240ba34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>03d76139-afea-44fb-8de3-0c0bfd9a90bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' customerNameSFa6K ' or . = ' customerNameSFa6K ')]</value>
      <webElementGuid>9d518d9c-3133-4f56-a29a-10fdd0af8492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
