<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sales_logo-transition ng-tns-c338-5</name>
   <tag></tag>
   <elementGuidId>14d85e39-2f0f-481c-a748-b3db76d5bc68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='logo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo-transition.ng-tns-c338-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cd322a9c-8ed9-42cf-83bf-69a303157430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>fdc071a3-5a83-4d99-b45f-71e99bd57af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-transition ng-tns-c338-5</value>
      <webElementGuid>bcebf210-9416-4262-9883-3d38ec979348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16448c13-c653-40e7-a328-74d3a7ff81eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/img/logo.png</value>
      <webElementGuid>eb342088-b4cb-4c6a-8c30-e06c5a1d4bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>nocollapse</value>
      <webElementGuid>df27dfb3-1ab8-4723-bbc9-4d688fe2edc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-oms-master[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-menu-display[@class=&quot;ng-tns-c338-5&quot;]/div[@class=&quot;ng-tns-c338-5 menu-transition ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c338-5&quot;]/img[@class=&quot;logo-transition ng-tns-c338-5&quot;]</value>
      <webElementGuid>903d67e3-f500-4739-b1ab-dfa0c84b277b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>69a80bd1-f9ac-43f7-9a3a-ff44011f50c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a5b728be-1469-4a09-93e3-5857631d0e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'logo' and @src = './assets/img/logo.png']</value>
      <webElementGuid>ad5d0fb2-b7ba-4d82-815e-9127475911cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
