<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>5455eaec-21cb-4753-b3e3-3f8183dfed31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-search-customerlist-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-search-customerlist-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45ef8b25-1a0c-450a-a7af-4d544904af91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-search-customerlist-customermanagement</value>
      <webElementGuid>df2a9528-eed6-41df-bd10-84c9794ef30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator prieds-btn-primary mat-raised-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>9144aa80-abcd-4845-b940-ef6b810238a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search </value>
      <webElementGuid>0d3c6807-46a9-49ab-b8c6-916625d74e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-search-customerlist-customermanagement&quot;)</value>
      <webElementGuid>32e5b9a6-1e37-46da-a04e-1ba418825929</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-search-customerlist-customermanagement']</value>
      <webElementGuid>065797ff-6723-45a9-b5aa-a52cdb844c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/div/div/button</value>
      <webElementGuid>5931c4d4-9f1d-42b3-8bfb-cb893ff75e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name'])[1]/following::button[1]</value>
      <webElementGuid>7096178f-ec32-43a7-bcef-8148d35d5229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer ID'])[1]/following::button[1]</value>
      <webElementGuid>39997b8c-3a96-4abc-a89f-82220d7bcfae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card/div/div/button</value>
      <webElementGuid>a4b8b744-25f3-47a9-85c1-baa39f6ff4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-search-customerlist-customermanagement' and (text() = ' Search ' or . = ' Search ')]</value>
      <webElementGuid>b6a81b2b-6be6-42d6-8eb0-94df0adae2be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
