<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Master</name>
   <tag></tag>
   <elementGuidId>cac1bd33-2cb9-44df-ac10-368e8aaa7f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Master > span.mat-button-wrapper > div > div.menu-title-transition > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Master']/span/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7c29ad5-c99e-4f37-95a8-b863e73514d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Master </value>
      <webElementGuid>8983e9f2-5ac0-4d7b-ab4d-85db1a8bc4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Master&quot;)/span[@class=&quot;mat-button-wrapper&quot;]/div[1]/div[@class=&quot;menu-title-transition&quot;]/div[1]</value>
      <webElementGuid>c2c6b08b-49c6-48fe-9fed-9015c55acd38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Master']/span/div/div/div</value>
      <webElementGuid>6d2ba3fb-50e9-4cb9-acdb-cf0eb5883a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warehouse'])[1]/following::div[5]</value>
      <webElementGuid>6a9863d0-3f30-49e7-9184-ac275fb93202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/following::div[10]</value>
      <webElementGuid>1dbef082-14a3-4d93-b91f-508a6e11f9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchasing'])[1]/preceding::div[4]</value>
      <webElementGuid>1a43452b-7b14-46e9-bf4b-6023d90a27e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting'])[1]/preceding::div[9]</value>
      <webElementGuid>dd6564bc-ecdb-4b2b-800e-f0e6f088dd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master']/parent::*</value>
      <webElementGuid>0b2aff67-0aee-495d-819e-6175d1f11d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-menu-element[3]/button/span/div/div/div</value>
      <webElementGuid>e051d19d-7dc2-4425-8a46-d1ba7e35f8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Master ' or . = ' Master ')]</value>
      <webElementGuid>a2874aae-4e32-4070-ab19-7dd1f7993389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
