<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>60eef27e-7fbc-45a6-93f2-5888e160e010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-search-customerlist-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-search-customerlist-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>387374aa-ed7d-4e3f-b882-2e687d8b3eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-search-customerlist-customermanagement</value>
      <webElementGuid>a7498ba9-ef0b-419a-abdf-51c1c9d45a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator prieds-btn-primary mat-raised-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>46ecbcf4-90fa-4dc9-b890-7d57f0be4c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search </value>
      <webElementGuid>aa0b4bf0-95f0-4336-894d-369de7029ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-search-customerlist-customermanagement&quot;)</value>
      <webElementGuid>f3cdd844-0d72-42ab-98ea-0c8e62ea9094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-search-customerlist-customermanagement']</value>
      <webElementGuid>0fb966dc-650c-43b7-950b-6c25c6e6c95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/div/div/button</value>
      <webElementGuid>77003d80-fa14-4f8f-ba62-819f03a7fd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name'])[1]/following::button[1]</value>
      <webElementGuid>1b7cdd15-d1d0-486a-9526-d0e669544c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer ID'])[1]/following::button[1]</value>
      <webElementGuid>d0e35d4a-06cf-4e93-9c17-f59ee2c5262e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card/div/div/button</value>
      <webElementGuid>598ce75e-e01f-4477-9afc-b74b13e16970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-search-customerlist-customermanagement' and (text() = ' Search ' or . = ' Search ')]</value>
      <webElementGuid>26a66820-5acb-4ce8-ae3f-df964991cc66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
