<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer ID_input-customername-custom_73c172</name>
   <tag></tag>
   <elementGuidId>0ec76c52-4b87-4a50-8df2-d570bd5a7bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-customername-customerlist-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-customername-customerlist-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53ba25df-1d39-4635-8873-5ed05fafd6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-customername-customerlist-customermanagement</value>
      <webElementGuid>4e078913-16e8-4f47-be3c-5a974eaae0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-42 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f554c877-07b1-4b9a-9234-8b76d0672358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68c3cc54-5fb8-4891-a6eb-ebde3c50b6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9aa183f4-3250-41c3-95b4-b1b1f3834d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-customername-customerlist-customermanagement&quot;)</value>
      <webElementGuid>d3ca0c7e-9f4e-4fb0-9e91-9f22f175880c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-customername-customerlist-customermanagement']</value>
      <webElementGuid>29e6c8d1-4834-450f-b672-6c915036a877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/div/div/mat-form-field[2]/div/div/div/input</value>
      <webElementGuid>42b1e7c3-0560-4ebb-93bb-8caf6f3375f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div/input</value>
      <webElementGuid>1af20a94-fde8-4eaf-8e04-ac436b8b1bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-customername-customerlist-customermanagement']</value>
      <webElementGuid>cd61358f-4597-480d-8d03-c0c0cae44cdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
