<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Register Import_input-custom_9d3571</name>
   <tag></tag>
   <elementGuidId>2ed6e47b-0f56-4367-9008-1e85208cf24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-customerid-customerlist-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-customerid-customerlist-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79486120-ec60-4437-aca5-be30b97ed535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-customerid-customerlist-customermanagement</value>
      <webElementGuid>8a6595d1-8eaf-4004-a591-19eb71e7c59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-41 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9b91e316-acbf-427e-a688-6b840944da20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bfb02825-f69a-4d79-b5a2-d379f44082af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4f21e077-3424-489a-b463-ea5c9404dfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-customerid-customerlist-customermanagement&quot;)</value>
      <webElementGuid>f1581006-4aa0-4989-94eb-f2f855450339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-customerid-customerlist-customermanagement']</value>
      <webElementGuid>3c22dbb8-f961-417c-9494-cfec4023d2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>405cabc9-29ab-4fef-b0e1-c05d4d1f9432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>48fb232d-54a9-4164-88a1-68eb699a4433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-customerid-customerlist-customermanagement']</value>
      <webElementGuid>bd52de8d-8e21-44d0-a820-1af3fe3a9ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
