<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log Out</name>
   <tag></tag>
   <elementGuidId>515596c7-5163-4718-9f85-a7164d6c2c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu-title-transition.ng-tns-c338-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-logout']/span/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90412096-ced7-49bd-bc25-de9230f7420d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title-transition ng-tns-c338-5</value>
      <webElementGuid>34942dc1-7835-422f-8989-5a3968e6afc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hide</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d5d6afe-f2ef-4067-af8d-e21c256ade2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Out</value>
      <webElementGuid>0bd87320-5977-4499-a05b-e7bc082fe63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-logout&quot;)/span[@class=&quot;mat-button-wrapper&quot;]/div[1]/div[@class=&quot;menu-title-transition ng-tns-c338-5&quot;]</value>
      <webElementGuid>3cbf43d3-4ce0-4e8c-8c98-281d7bcd242a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button-logout']/span/div/div</value>
      <webElementGuid>edd372dc-a241-4fde-8550-7352c540e273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[4]</value>
      <webElementGuid>f879258b-9238-4a5a-bcb8-43f1432a194f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace'])[1]/following::div[9]</value>
      <webElementGuid>6f2fe1ff-5ccb-4f28-9491-09f0a38c8bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salesman: REYNER'])[1]/preceding::div[4]</value>
      <webElementGuid>f11ff458-e808-4ece-9ed1-e28bae32a790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location : SITE A'])[1]/preceding::div[6]</value>
      <webElementGuid>0622b0cf-b928-4e7e-8cae-af61ef7f10f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log Out']/parent::*</value>
      <webElementGuid>bfe4d09a-ebc4-4556-9160-ab83ccbdc771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span/div/div</value>
      <webElementGuid>2437c4c8-fd08-45a7-b784-de8bf9279c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Log Out' or . = 'Log Out')]</value>
      <webElementGuid>791e9e65-bc31-4c61-8c02-b72d0ea2cdf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
